import io
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)

from apps.core.models import Company, AnnualReport, FinancialMetric


PRIMARY = colors.HexColor('#0F172A')
ACCENT = colors.HexColor('#2563EB')
SUCCESS = colors.HexColor('#16A34A')
LIGHT_BG = colors.HexColor('#F1F5F9')
BORDER = colors.HexColor('#CBD5E1')
TEXT = colors.HexColor('#1E293B')
MUTED = colors.HexColor('#64748B')


def _styles():
    ss = getSampleStyleSheet()
    return {
        'title': ParagraphStyle('title', parent=ss['Title'], fontSize=20, textColor=PRIMARY, spaceAfter=6, alignment=TA_CENTER, fontName='Helvetica-Bold'),
        'subtitle': ParagraphStyle('subtitle', parent=ss['Normal'], fontSize=10, textColor=MUTED, spaceAfter=20, alignment=TA_CENTER),
        'h2': ParagraphStyle('h2', parent=ss['Heading2'], fontSize=13, textColor=ACCENT, spaceBefore=16, spaceAfter=10, fontName='Helvetica-Bold'),
        'footer': ParagraphStyle('footer', parent=ss['Normal'], fontSize=8, textColor=MUTED, alignment=TA_CENTER),
    }


def _latest_metric(company):
    """Get latest FinancialMetric for a company."""
    latest = AnnualReport.objects.filter(company=company).order_by('-year').first()
    if not latest:
        return None
    return FinancialMetric.objects.filter(report=latest).first()


def generate_comparison_pdf(company_id_a, company_id_b):
    """Generate a side-by-side comparison PDF between two companies."""
    company_a = Company.objects.get(company_id=company_id_a)
    company_b = Company.objects.get(company_id=company_id_b)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm,
        title=f'Comparison: {company_a.company_name} vs {company_b.company_name}',
    )

    styles = _styles()
    story = []

    # Header
    story.append(Paragraph(
        f"{company_a.company_name} vs {company_b.company_name}",
        styles['title']
    ))
    story.append(Paragraph(
        f"Comparative Intelligence Report · {datetime.now().strftime('%B %d, %Y')}",
        styles['subtitle']
    ))

    metric_a = _latest_metric(company_a)
    metric_b = _latest_metric(company_b)

    cell_style = ParagraphStyle('cell', fontName='Helvetica', fontSize=9, leading=11, textColor=TEXT)
    cell_num = ParagraphStyle('cell_num', fontName='Helvetica', fontSize=9, leading=11, textColor=TEXT, alignment=2)
    cell_head = ParagraphStyle('cell_head', fontName='Helvetica-Bold', fontSize=9, leading=11, textColor=colors.white)
    cell_head_num = ParagraphStyle('cell_head_num', fontName='Helvetica-Bold', fontSize=9, leading=11, textColor=colors.white, alignment=2)

    # Metrics comparison
    story.append(Paragraph("Financial Comparison (Latest Year)", styles['h2']))

    data = [[
        Paragraph('<b>Metric</b>', cell_head),
        Paragraph(f'<b>{company_a.company_name[:25]}</b>', cell_head_num),
        Paragraph(f'<b>{company_b.company_name[:25]}</b>', cell_head_num),
    ]]

    def _val(m, field):
        if not m:
            return '—'
        v = getattr(m, field, None)
        return f"{v:,.0f}" if v else '—'

    rows = [
        ('Revenue', _val(metric_a, 'revenue'), _val(metric_b, 'revenue')),
        ('Profit', _val(metric_a, 'profit'), _val(metric_b, 'profit')),
        ('Assets', _val(metric_a, 'assets'), _val(metric_b, 'assets')),
        ('Debt', _val(metric_a, 'debt'), _val(metric_b, 'debt')),
        ('Profit Margin',
            f"{metric_a.profit_margin:.2f}%" if metric_a and metric_a.profit_margin else '—',
            f"{metric_b.profit_margin:.2f}%" if metric_b and metric_b.profit_margin else '—'),
    ]

    for label, a, b in rows:
        data.append([
            Paragraph(label, cell_style),
            Paragraph(a, cell_num),
            Paragraph(b, cell_num),
        ])

    table = Table(data, colWidths=[4.5*cm, 5.5*cm, 5.5*cm], repeatRows=1)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), PRIMARY),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ('GRID', (0, 0), (-1, -1), 0.25, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
    ]))
    story.append(table)

    # Footer
    story.append(Spacer(1, 30))
    story.append(Paragraph(
        f"Generated by CPIP · {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        styles['footer']
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer