# Generated by Django 4.2 on 2026-09-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'db_table': 'annual_reports',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('risk_id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_type', models.CharField(max_length=100)),
                ('severity', models.IntegerField()),
                ('description', models.TextField()),
                ('risk_category', models.CharField(choices=[('operational', 'Operational'), ('financial', 'Financial'), ('market', 'Market'), ('compliance', 'Compliance')], default='financial', max_length=50)),
                ('detected_date', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.annualreport')),
            ],
            options={
                'db_table': 'risks',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation_text', models.TextField()),
                ('mitigation_steps', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('expected_impact', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.risk')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('forecast_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('revenue', 'Revenue'), ('profit', 'Profit'), ('segment', 'Segment')], max_length=50)),
                ('forecast_year', models.IntegerField()),
                ('projected_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('confidence_interval_lower', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('confidence_interval_upper', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.company')),
            ],
            options={
                'db_table': 'forecasts',
            },
        ),
        migrations.CreateModel(
            name='FinancialMetric',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('revenue_growth_yoy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_growth_yoy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_metrics', to='core.annualreport')),
            ],
            options={
                'db_table': 'financial_metrics',
            },
        ),
        migrations.CreateModel(
            name='ExecutiveReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('generation_date', models.DateTimeField(auto_now_add=True)),
                ('report_content', models.JSONField(blank=True, null=True)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_reports', to='core.company')),
            ],
            options={
                'db_table': 'executive_reports',
            },
        ),
        migrations.CreateModel(
            name='BusinessSegment',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('segment_name', models.CharField(max_length=255)),
                ('segment_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('segment_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('segment_growth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('segment_profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.annualreport')),
            ],
            options={
                'db_table': 'business_segments',
            },
        ),
        migrations.AddField(
            model_name='annualreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.company'),
        ),
    ]
